project:
  type: book
  output-dir: docs

book:
  title: "Remote Sensing & Earth Observation Exploration - Nikhil Desai"
  author: "Nikhil Desai"
  date: "3/14/2024"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - Week9.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual

